In [2]:
import pandas as pd

In [3]:
list1 = ['A', 'B' , 'C', 'D']
s1 = pd.Series(list1)
s1

0    A
1    B
2    C
3    D
dtype: str

In [4]:
df = pd.DataFrame(list1)
df

   0
0  A
1  B
2  C
3  D

In [5]:
dict1 = {'name': ['A', 'B' , 'C', 'D'] , 'marks' :[1,2,3,4]}
df = pd.DataFrame(dict1)
df

  name  marks
0    A      1
1    B      2
2    C      3
3    D      4

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   marks   4 non-null      int64
dtypes: int64(1), str(1)
memory usage: 196.0 bytes

In [7]:
df = pd.read_csv("Bookstore.csv")
df

,S No,Product_Name,Product_Author,Book_Format,Sales_Price,Product_Rating,Genre,State,Region,Date,Cost_Price,Page_Count
0,0,Lessons in Chemistry,Bonnie Garmus,Paperback,9.99,5.0,Sci-Fi,Missouri,Midwest,01-01-2023,7.74,250.0
1,1,Demon Copperhead,Barbara Kingsolver,Paperback,10.40,5.0,Romance,Virginia,South,01-01-2023,8.06,95.0
2,2,It Ends With Us,Colleen Hoover,Paperback,62.00,5.0,Comedy,Texas,South,01-01-2023,48.05,551.0
3,3,Yellowface,Rebecca F Kuang,Hardcover,16.90,4.5,Poetry,California,West,01-01-2023,13.10,169.0
4,4,It Starts with Us,Colleen Hoover,Hardcover,14.90,5.0,Sci-Fi,South Carolina,South,01-01-2023,11.55,119.0
...,...,...,...,...,...,...,...,...,...,...,...,...
29349,29935,Nightchaser,Amanda Bouchet,Paperback,9.99,4.5,Comedy,Pennsylvania,Northeast,01-12-2023,6.99,61.0
29350,29936,Crown of Ruin,Keary Taylor,Paperback,13.60,4.0,Romance,Connecticut,Northeast,01-12-2023,9.52,138.0
29351,29937,Firebird,Peter Morwood,Paperback,4.99,4.5,Sci-Fi,North Carolina,South,01-12-2023,3.49,92.0
29352,29938,Selling Out,Justina Robson,Paperback,8.99,4.5,Comedy,Pennsylvania,Northeast,01-12-2023,6.29,162.0
29353,29939,The Oracle's Queen,Lynn Flewelling,Paperback,11.90,4.5,Comedy,California,West,01-12-2023,8.33,158.0

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 29354 entries, 0 to 29353
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   S No            29354 non-null  int64
 1   Product_Name    29354 non-null  str
 2   Product_Author  29354 non-null  str
 3   Book_Format     29354 non-null  str
 4   Sales_Price     29354 non-null  float64
 5   Product_Rating  29354 non-null  float64
 6   Genre           29354 non-null  str
 7   State           29354 non-null  str
 8   Region          29354 non-null  str
 9   Date            29354 non-null  str
 10  Cost_Price      29354 non-null  float64
 11  Page_Count      25755 non-null  float64
dtypes: float64(4), int64(1), str(7)
memory usage: 2.7 MB

In [9]:
df.describe()

               S No   Sales_Price  Product_Rating    Cost_Price    Page_Count
count  29354.000000  29354.000000    29354.000000  29354.000000  25755.000000
mean   14919.314267     15.394405        4.259522     11.348545    159.003533
std     8632.335160     15.849701        0.696120     11.750629     84.995178
min        0.000000      2.370000        1.000000      1.720000     50.000000
25%     7459.250000      8.990000        4.000000      6.830000    116.000000
50%    14869.500000     10.100000        4.500000      7.640000    143.000000
75%    22374.750000     14.900000        4.500000     10.730000    174.000000
max    29939.000000     99.000000        5.000000     76.730000    911.000000

In [10]:
df.tail()

,S No,Product_Name,Product_Author,Book_Format,Sales_Price,Product_Rating,Genre,State,Region,Date,Cost_Price,Page_Count
29349,29935,Nightchaser,Amanda Bouchet,Paperback,9.99,4.5,Comedy,Pennsylvania,Northeast,01-12-2023,6.99,61.0
29350,29936,Crown of Ruin,Keary Taylor,Paperback,13.60,4.0,Romance,Connecticut,Northeast,01-12-2023,9.52,138.0
29351,29937,Firebird,Peter Morwood,Paperback,4.99,4.5,Sci-Fi,North Carolina,South,01-12-2023,3.49,92.0
29352,29938,Selling Out,Justina Robson,Paperback,8.99,4.5,Comedy,Pennsylvania,Northeast,01-12-2023,6.29,162.0
29353,29939,The Oracle's Queen,Lynn Flewelling,Paperback,11.90,4.5,Comedy,California,West,01-12-2023,8.33,158.0

In [11]:
df1=df[['Product_Name']]
print(type(df1))
df1

<class 'pandas.DataFrame'>

               Product_Name
0      Lessons in Chemistry
1          Demon Copperhead
2           It Ends With Us
3                Yellowface
4         It Starts with Us
...                     ...
29349           Nightchaser
29350         Crown of Ruin
29351              Firebird
29352           Selling Out
29353    The Oracle's Queen

[29354 rows x 1 columns]

In [12]:
df.loc[[3,6,9],['Product_Name','Sales_Price']]

        Product_Name  Sales_Price
3         Yellowface        16.90
6  The Guilty Couple         8.99
9  Shrines of Gaiety        10.40

In [13]:
df.loc[range(1000,1010),['Product_Name','Sales_Price']]

                                           Product_Name  Sales_Price
1000                                         The Appeal         8.99
1001                                       Here and Now         8.99
1002                                           Imperium         9.99
1003                             Before They Are Hanged        10.40
1004  The Hundred-Year-Old Man Who Climbed Out of th...         8.99
1005                      I Have Some Questions For You        16.90
1006                         The Picture of Dorian Gray        16.90
1007                         Secrets of the Villa Amore        16.90
1008                                         Dirty Game        10.40
1009                                    The Night Tiger         9.99

In [14]:
for i in range (5,11):
    print(i)

5
6
7
8
9
10

In [15]:
df['Profit'] = df['Sales_Price'] - df['Cost_Price']
df

,S No,Product_Name,Product_Author,Book_Format,Sales_Price,Product_Rating,Genre,State,Region,Date,Cost_Price,Page_Count,Profit
0,0,Lessons in Chemistry,Bonnie Garmus,Paperback,9.99,5.0,Sci-Fi,Missouri,Midwest,01-01-2023,7.74,250.0,2.25
1,1,Demon Copperhead,Barbara Kingsolver,Paperback,10.40,5.0,Romance,Virginia,South,01-01-2023,8.06,95.0,2.34
2,2,It Ends With Us,Colleen Hoover,Paperback,62.00,5.0,Comedy,Texas,South,01-01-2023,48.05,551.0,13.95
3,3,Yellowface,Rebecca F Kuang,Hardcover,16.90,4.5,Poetry,California,West,01-01-2023,13.10,169.0,3.80
4,4,It Starts with Us,Colleen Hoover,Hardcover,14.90,5.0,Sci-Fi,South Carolina,South,01-01-2023,11.55,119.0,3.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29349,29935,Nightchaser,Amanda Bouchet,Paperback,9.99,4.5,Comedy,Pennsylvania,Northeast,01-12-2023,6.99,61.0,3.00
29350,29936,Crown of Ruin,Keary Taylor,Paperback,13.60,4.0,Romance,Connecticut,Northeast,01-12-2023,9.52,138.0,4.08
29351,29937,Firebird,Peter Morwood,Paperback,4.99,4.5,Sci-Fi,North Carolina,South,01-12-2023,3.49,92.0,1.50
29352,29938,Selling Out,Justina Robson,Paperback,8.99,4.5,Comedy,Pennsylvania,Northeast,01-12-2023,6.29,162.0,2.70
29353,29939,The Oracle's Queen,Lynn Flewelling,Paperback,11.90,4.5,Comedy,California,West,01-12-2023,8.33,158.0,3.57

In [16]:
list1 =[1,2,3,4,5]
list2 =[9,8,7,6,5]

print(list1 + list2)

[1, 2, 3, 4, 5, 9, 8, 7, 6, 5]

In [17]:
list1 =[1,2,3,4,5]
list2 =[9,8,7,6,5]
list3 = []

for i in range (5):
    
    list3.append(list1[i] == list2[i])

print (list3)

[False, False, False, False, True]

In [18]:
#if sales price is <20, tag it cheap, between 20 and 50 tag as moderate and >50 tag as expensive

def function1(i):
    if i < 20: 
        return 'cheap'
    elif i<50:
        return 'moderate'
    elif i>=50:
        return 'expensive'

df['Affordability'] = df['Sales_Price'].apply(function1)
df

,S No,Product_Name,Product_Author,Book_Format,Sales_Price,Product_Rating,Genre,State,Region,Date,Cost_Price,Page_Count,Profit,Affordability
0,0,Lessons in Chemistry,Bonnie Garmus,Paperback,9.99,5.0,Sci-Fi,Missouri,Midwest,01-01-2023,7.74,250.0,2.25,cheap
1,1,Demon Copperhead,Barbara Kingsolver,Paperback,10.40,5.0,Romance,Virginia,South,01-01-2023,8.06,95.0,2.34,cheap
2,2,It Ends With Us,Colleen Hoover,Paperback,62.00,5.0,Comedy,Texas,South,01-01-2023,48.05,551.0,13.95,expensive
3,3,Yellowface,Rebecca F Kuang,Hardcover,16.90,4.5,Poetry,California,West,01-01-2023,13.10,169.0,3.80,cheap
4,4,It Starts with Us,Colleen Hoover,Hardcover,14.90,5.0,Sci-Fi,South Carolina,South,01-01-2023,11.55,119.0,3.35,cheap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29349,29935,Nightchaser,Amanda Bouchet,Paperback,9.99,4.5,Comedy,Pennsylvania,Northeast,01-12-2023,6.99,61.0,3.00,cheap
29350,29936,Crown of Ruin,Keary Taylor,Paperback,13.60,4.0,Romance,Connecticut,Northeast,01-12-2023,9.52,138.0,4.08,cheap
29351,29937,Firebird,Peter Morwood,Paperback,4.99,4.5,Sci-Fi,North Carolina,South,01-12-2023,3.49,92.0,1.50,cheap
29352,29938,Selling Out,Justina Robson,Paperback,8.99,4.5,Comedy,Pennsylvania,Northeast,01-12-2023,6.29,162.0,2.70,cheap
29353,29939,The Oracle's Queen,Lynn Flewelling,Paperback,11.90,4.5,Comedy,California,West,01-12-2023,8.33,158.0,3.57,cheap

In [19]:
list1 = df['Profit'].tolist()
print(type(list1))
print(sum(list1))
print(list1)

<class 'list'>
118762.15000000001

In [20]:
df[[i>50 for i in df['Sales_Price']]]

,S No,Product_Name,Product_Author,Book_Format,Sales_Price,Product_Rating,Genre,State,Region,Date,Cost_Price,Page_Count,Profit,Affordability
2,2,It Ends With Us,Colleen Hoover,Paperback,62.0,5.0,Comedy,Texas,South,01-01-2023,48.05,551.0,13.95,expensive
14,14,How to Kill Your Family,Bella Mackie,Digital,86.0,4.5,Thriller,Ohio,Midwest,01-01-2023,66.65,NaN,19.35,expensive
20,20,One of the Girls,Lucy Clarke,Paperback,94.0,4.5,Non Fiction,California,West,01-01-2023,72.85,377.0,21.15,expensive
35,35,The Fall,Louise Jensen,Paperback,76.0,4.0,Thriller,Nevada,West,01-01-2023,58.90,320.0,17.10,expensive
43,43,Malibu Rising,Taylor Jenkins Reid,Digital,97.0,5.0,Non Fiction,Washington,West,01-01-2023,75.17,NaN,21.83,expensive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29202,29785,Cold Boy's Wood,Carol Birch,Paperback,96.0,1.0,Non Fiction,Arizona,West,01-12-2023,67.20,548.0,28.80,expensive
29206,29789,Alice Payne Arrives,Kate Heartfield,Paperback,92.0,4.0,Non Fiction,California,West,01-12-2023,64.40,577.0,27.60,expensive
29231,29814,Late Eclipses (Toby Daye Book 4),Seanan McGuire,Paperback,80.0,5.0,Fantasy,Missouri,Midwest,01-12-2023,56.00,376.0,24.00,expensive
29305,29890,The Devil's Blade,Mark Alder,Paperback,75.0,4.0,Sci-Fi,Missouri,Midwest,01-12-2023,52.50,505.0,22.50,expensive
29316,29901,Wild Hunger,Chloe Neill,Paperback,65.0,4.0,Thriller,California,West,01-12-2023,45.50,445.0,19.50,expensive

In [21]:
df[[len(i)>20 for i in df['Product_Author']]]

,S No,Product_Name,Product_Author,Book_Format,Sales_Price,Product_Rating,Genre,State,Region,Date,Cost_Price,Page_Count,Profit,Affordability
27,27,The Paper Palace,Miranda Cowley Heller,Paperback,9.99,4.5,Sci-Fi,California,West,01-01-2023,7.74,83.0,2.25,cheap
191,193,Sea of Tranquility,Emily St. John Mandel,Paperback,9.99,4.0,Fantasy,California,West,01-01-2023,7.74,203.0,2.25,cheap
215,217,Dr Jekyll and Mr Hyde,Robert Louis Stevenson,Paperback,5.47,4.5,Thriller,California,West,01-01-2023,4.24,67.0,1.23,cheap
319,323,Shantaram,Gregory David Roberts,Paperback,10.90,5.0,Comedy,California,West,01-01-2023,8.45,217.0,2.45,cheap
361,365,People Person,Candice Carty-Williams,Paperback,8.99,4.5,Sci-Fi,New Hampshire,Northeast,01-01-2023,6.97,152.0,2.02,cheap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29174,29756,E-Day II,Nicholas Sansbury Smith,Digital,14.90,4.0,Thriller,California,West,01-12-2023,10.43,NaN,4.47,cheap
29244,29827,The Kindness,John Ajvide Lindqvist,Hardcover,25.00,4.0,Thriller,Georgia,South,01-12-2023,17.50,96.0,7.50,moderate
29317,29902,The Iron Tree (Crowthistle Chronicles),Cecilia Dart-Thornton,Digital,7.99,4.5,Fantasy,California,West,01-12-2023,5.59,NaN,2.40,cheap
29319,29905,Strange Tales #4,John Gregory Betancourt,Paperback,12.10,4.5,Sci-Fi,Pennsylvania,Northeast,01-12-2023,8.47,72.0,3.63,cheap
29339,29925,Handbook of Vance Space,Michael Andre-Driussi,Paperback,13.90,4.0,Fantasy,North Carolina,South,01-12-2023,9.73,205.0,4.17,cheap

In [22]:

df1 = df[[i>50 for i in df['Sales_Price']]]

df2 = df1[[len(i)>20 for i in df1['Product_Author']]]

In [23]:
df['Sales_Price'].sum()
df['Sales_Price'].mean()
df['Sales_Price'].median()
df['Sales_Price'].std()
df['Sales_Price'].max()
df['Sales_Price'].min()
df['Sales_Price'].count()

np.int64(29354)

In [24]:
#format wise total sales

df.groupby("Book_Format")['Sales_Price'].sum()

Book_Format
Audio          7436.55
Digital       44975.38
Hardcover     88343.19
Others         1667.28
Paperback    309464.95
Name: Sales_Price, dtype: float64

In [25]:
import pandas as pd

df = pd.read_csv("Bookstore.csv")
df

df.groupby(["Region","Book_Format"])['Sales_Price'].sum()

Region     Book_Format
Midwest    Audio            1346.31
           Digital          8742.76
           Hardcover       20118.05
           Others            414.37
           Paperback       63880.88
Northeast  Audio            1379.21
           Digital          7315.93
           Hardcover       15277.47
           Others            340.63
           Paperback       50020.46
South      Audio            1479.36
           Digital          7964.97
           Hardcover       16549.48
           Others            203.52
           Paperback       57721.21
West       Audio            3231.67
           Digital         20951.72
           Hardcover       36398.19
           Others            708.76
           Paperback      137842.40
Name: Sales_Price, dtype: float64

In [26]:
import pandas as pd

df = pd.read_csv("Bookstore.csv")
df

df.groupby(["Region","Book_Format"])[['Sales_Price','Cost_Price']].agg(['sum','mean','max'])

                      Sales_Price                  Cost_Price             \
                              sum       mean   max        sum       mean
Region    Book_Format
Midwest   Audio           1346.31  13.599091  71.0     995.82  10.058788
          Digital         8742.76  12.933077  89.0    6446.83   9.536731
          Hardcover      20118.05  16.920143  91.0   14853.99  12.492843
          Others           414.37  19.731905  77.0     309.20  14.723810
          Paperback      63880.88  13.746692  91.0   47092.55  10.133968
Northeast Audio           1379.21  15.324556  84.0    1015.54  11.283778
          Digital         7315.93  14.486990  91.0    5387.05  10.667426
          Hardcover      15277.47  16.587915  90.0   11293.52  12.262237
          Others           340.63  17.927895  79.0     249.30  13.121053
          Paperback      50020.46  13.952709  91.0   36861.65  10.282190
South     Audio           1479.36  12.644103  62.0    1086.55   9.286752
          Digital         7964.97  13.230847  91.0    5855.31   9.726429
          Hardcover      16549.48  16.320986  77.0   12218.02  12.049329
          Others           203.52  11.971765  20.0     150.59   8.858235
          Paperback      57721.21  13.220616  91.0   42515.49   9.737858
West      Audio           3231.67  16.658093  98.0    2374.73  12.240876
          Digital        20951.72  17.215875  99.0   15427.11  12.676343
          Hardcover      36398.19  19.402020  99.0   26862.54  14.319051
          Others           708.76  16.875238  93.0     515.58  12.275714
          Paperback     137842.40  16.898664  99.0  101613.83  12.457255


                         max
Region    Book_Format
Midwest   Audio        54.31
          Digital      66.75
          Hardcover    68.25
          Others       58.52
          Paperback    70.53
Northeast Audio        60.90
          Digital      67.50
          Hardcover    67.50
          Others       56.88
          Paperback    69.61
South     Audio        44.33
          Digital      69.61
          Hardcover    58.91
          Others       14.70
          Paperback    68.98
West      Audio        74.48
          Digital      75.73
          Hardcover    76.73
          Others       66.24
          Paperback    76.73

In [27]:
import pandas as pd

df = pd.read_csv("Bookstore.csv")
df

df.groupby(["Region","Book_Format"])[['Sales_Price','Profit']].agg(['sum','mean','max'])

KeyError: "Columns not found: 'Profit'"